// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7704yTgcr4LKEqqnGUgrheYVAns278ew',
    appId: '1:222912676291:android:83c499d9e2f208eae63d76',
    messagingSenderId: '222912676291',
    projectId: 'rent-machine-3dddc',
    databaseURL: 'https://rent-machine-3dddc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rent-machine-3dddc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmGqN-LwzzRXHu2SYSCuVE8KGZmlGgD-c',
    appId: '1:222912676291:ios:3e1c9ec49b894653e63d76',
    messagingSenderId: '222912676291',
    projectId: 'rent-machine-3dddc',
    databaseURL: 'https://rent-machine-3dddc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rent-machine-3dddc.appspot.com',
    iosBundleId: 'np.com.rajeshadhikari.rentMechine',
  );
}
